#
# Makefile for OME_Tools
#
# $Id: Makefile,v 1.5 2003/12/19 15:07:13 tetsuyak Exp $
#

include ../../dist/config.mk

IDETARGETS=kcpassword resolvalias pppdiscon soundplay speaking	\
makenewalias updatefinder mergeres
installdir=$(omeappdir)/tools

include ../../dist/idebuild.mk
