// _MainMenu_EOArchive_English.java
// Generated by EnterpriseObjects palette at \u6708\u66dc\u65e5, 12 23, 2002 18:22:07 Asia/Tokyo

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _MainMenu_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    ASKNibObjectInfo _aSKNibObjectInfo0, _aSKNibObjectInfo1, _aSKNibObjectInfo2, _aSKNibObjectInfo3, _aSKNibObjectInfo4, _aSKNibObjectInfo5, _aSKNibObjectInfo6, _aSKNibObjectInfo7;
    ASKNibObjectInfoManager _aSKNibObjectInfoManager0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton2;
    javax.swing.JPanel _nsView0;
    javax.swing.JRadioButton _jRadioButton0, _jRadioButton1;

    public _MainMenu_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _aSKNibObjectInfo7 = (ASKNibObjectInfo)_registered(new ASKNibObjectInfo(), "");
        _aSKNibObjectInfo6 = (ASKNibObjectInfo)_registered(new ASKNibObjectInfo(), "");
        _aSKNibObjectInfo5 = (ASKNibObjectInfo)_registered(new ASKNibObjectInfo(), "");
        _aSKNibObjectInfo4 = (ASKNibObjectInfo)_registered(new ASKNibObjectInfo(), "");
        _aSKNibObjectInfo3 = (ASKNibObjectInfo)_registered(new ASKNibObjectInfo(), "");
        _aSKNibObjectInfo2 = (ASKNibObjectInfo)_registered(new ASKNibObjectInfo(), "");
        _aSKNibObjectInfo1 = (ASKNibObjectInfo)_registered(new ASKNibObjectInfo(), "");
        _aSKNibObjectInfo0 = (ASKNibObjectInfo)_registered(new ASKNibObjectInfo(), "");
        _aSKNibObjectInfoManager0 = (ASKNibObjectInfoManager)_registered(new ASKNibObjectInfoManager(), "AppleScript Info");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cancel"), "NSButton2");
        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Set"), "NSButton1");
        _jRadioButton1 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Mail Writer Application"), "NSButtonCell1");
        _jRadioButton0 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Mail Reader Application"), "NSButtonCell");
        _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(2, 1, 4, 2), "NSMatrix1");
        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Select"), "NSButton");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window");
        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "unhideAllApplications", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "hide", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "orderFrontStandardAboutPanel", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "terminate", ), ""));
        .addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "hideOtherApplications", ), ""));
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsTextField2, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("Please select the Application.");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _setFontForComponent(_nsButton2, "Lucida Grande", 13, Font.PLAIN);
        _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jRadioButton1, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_jRadioButton0, "Lucida Grande", 13, Font.PLAIN);
        _jRadioButton0.setSize(171, 18);
        _jRadioButton0.setLocation(0, 0);
        _nsMatrix0.add(_jRadioButton0);
        _jRadioButton1.setSize(171, 18);
        _jRadioButton1.setLocation(0, 20);
        _nsMatrix0.add(_jRadioButton1);
        _setFontForComponent(_nsMatrix0, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsTextField1, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(true);
        _nsTextField1.setText("");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(true);
        _nsTextField1.setEnabled(true);
        _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Target Application");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(133, 17);
        _nsTextField0.setLocation(11, 14);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField0);
        _nsTextField1.setSize(305, 22);
        _nsTextField1.setLocation(149, 11);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField1);
        _nsButton0.setSize(77, 26);
        _nsButton0.setLocation(380, 34);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton0);
        _nsMatrix0.setSize(171, 38);
        _nsMatrix0.setLocation(146, 60);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix0);
        _nsButton1.setSize(77, 26);
        _nsButton1.setLocation(380, 114);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton1);
        _nsButton2.setSize(77, 26);
        _nsButton2.setLocation(296, 114);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton2);
        _nsTextField2.setSize(214, 13);
        _nsTextField2.setLocation(149, 41);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField2);
        _nsView0.setSize(466, 150);
        _eoFrame0.setTitle("OME - Editor Setup");
        _eoFrame0.setLocation(252, 524);
        _eoFrame0.setSize(466, 150);
    }
}
