// _Window4_EOArchive_Japanese.java
// Generated by EnterpriseObjects palette at 2005\u5e747\u670823\u65e5\u571f\u66dc\u65e5 0\u664207\u520622\u79d2Asia/Tokyo

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _Window4_EOArchive_Japanese extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOTextArea _nsTextView0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3, _nsTextField4;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox2, _nsBox3;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton2, _nsButton3;
    javax.swing.JPanel _nsView0;

    public _Window4_EOArchive_Japanese(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView1");
        _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox21");
        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsTextView0 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "NSTextView");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField3");
        _nsButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton("\u4f55\u3082\u3057\u306a\u3044\u3067\u7d42\u4e86"), "NSButton4");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField4");
        _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("\u8a2d\u5b9a\u3059\u308b"), "NSButton2");
        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("\u30d5\u30a9\u30eb\u30c0\u6307\u5b9a"), "NSButton");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "mailBoxPath")) != null)) {
            _nsTextField0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField0");
        } else {
            _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        }

        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("\u524d\u3078"), "NSButton3");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window4");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "showFinishPanel", _nsButton2), ""));
        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "selectFolder", _nsButton1), ""));

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _connect(_owner(), _nsTextField0, "mailBoxPath");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "showWindow3", _nsButton0), ""));
    }

    protected void _init() {
        super._init();
        if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
        _nsBox3.setSize(470, 1);
        _nsBox3.setLocation(2, 2);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsBox3, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsBox3);
        _nsBox2.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField4, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("\u30e1\u30fc\u30eb\u30dc\u30c3\u30af\u30b9\u30d5\u30a9\u30eb\u30c0");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);
        _nsTextView0.setEditable(true);
        _nsTextView0.setOpaque(true);
        _nsTextView0.setText("\u3053\u3053\u3067\u306f\u53d7\u4fe1\u30e1\u30fc\u30eb\u30b5\u30fc\u30d0\u306f1\u3064\u3060\u3051\u3092\u6307\u5b9a\u3057\u307e\u3057\u305f\u304c\u3001\u8907\u6570\u306e\u30b5\u30fc\u30d0\u3092\u6307\u5b9a\u3057\u3066\u3001\u307e\u3068\u3081\u3066\u30e1\u30fc\u30eb\u3092\u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u3059\u308b\u3059\u308b\u3053\u3068\u304c\u3067\u304d\u307e\u3059\u3002\u8a2d\u5b9a\u306f\u3001OME\u8a2d\u5b9a\u30d5\u30a9\u30eb\u30c0\uff08OME_Preferences\u30d5\u30a9\u30eb\u30c0\uff09\u306eReceive_Info.txt\u30d5\u30a1\u30a4\u30eb\u3092\u7de8\u96c6\u3057\u3066\u8ffd\u52a0\u3057\u3066\u304f\u3060\u3055\u3044\u3002\n\n\u3053\u3053\u3067\u5165\u529b\u3057\u305f\u30d1\u30b9\u30ef\u30fc\u30c9\u306f\u3001\u3068\u308a\u3042\u3048\u305a\u306f\u78ba\u8a8d\u3057\u3084\u3059\u3044\u3088\u3046\u306b\u30c6\u30ad\u30b9\u30c8\u30d5\u30a1\u30a4\u30eb\u306b\u305d\u306e\u307e\u307e\u8a18\u9332\u3055\u308c\u307e\u3059\u304c\u3001Keychain\u306b\u30d1\u30b9\u30ef\u30fc\u30c9\u3092\u8a18\u9332\u3059\u308b\u3053\u3068\u3082\u3067\u304d\u307e\u3059\u3002\n\n\u30e1\u30fc\u30eb\u306e\u30d5\u30a9\u30eb\u30c0\u3078\u306e\u632f\u308a\u5206\u3051\u3082\u3082\u3061\u308d\u3093\u3067\u304d\u307e\u3059\u3002OME_Preferences\u30d5\u30a9\u30eb\u30c0\u306eMoving_Info.txt\u30d5\u30a1\u30a4\u30eb\u306b\u8a2d\u5b9a\u3092\u8a18\u8ff0\u3059\u308b\u3053\u3068\u3067\u53ef\u80fd\u3067\u3059\u3002\u8a73\u7d30\u306f\u3001Web\u30b5\u30a4\u30c8\u306e\u30de\u30cb\u30e5\u30a2\u30eb\u30da\u30fc\u30b8\u3092\u5fa1\u89a7\u4e0b\u3055\u3044\u3002");
        _setFontForComponent(_nsTextView0.textArea(), "Hiragino Kaku Gothic Pro", 12, Font.PLAIN);
        _setFontForComponent(_nsTextField3, "Lucida Grande", 18, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(false);
        _nsTextField3.setText("\u3053\u308c\u304b\u3089\u8a2d\u5b9a\u3092\u884c\u3044\u307e\u3059");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(null);
        _setFontForComponent(_nsTextField2, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("\u8ffd\u52a0\u60c5\u5831");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(null, "terminate", _nsButton3), ""));
        _setFontForComponent(_nsButton3, "Lucida Grande", 11, Font.PLAIN);
        _nsButton3.setMargin(new Insets(0, 2, 0, 2));
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(527, 1);
        _nsBox1.setLocation(2, 2);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField1, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("\u53d7\u4fe1\u3057\u305f\u30e1\u30fc\u30eb\u3092\u4fdd\u5b58\u3059\u308b\u30d5\u30a9\u30eb\u30c0\u3092\u7528\u610f\u3057\u307e\u3059\u3002\u4ee5\u4e0b\u306e\u6b04\u3092\u7a7a\u6b04\u306e\u307e\u307e\u306b\u3057\u3066\u304a\u304f\u3068\u3001\u73fe\u5728\u306e\u30e6\u30fc\u30b6\u306e\u30eb\u30fc\u30c8\u30d5\u30a9\u30eb\u30c0\u306b\u30e1\u30fc\u30eb\u30dc\u30c3\u30af\u30b9\u30d5\u30a9\u30eb\u30c0\u3092\u4f5c\u308a\u307e\u3059\u3002\u5225\u306e\u5834\u6240\u306b\u4f5c\u308a\u305f\u3044\u3068\u304d\u306b\u306f\u3001\u30d5\u30a9\u30eb\u30c0\u6307\u5b9a\u30dc\u30bf\u30f3\u3092\u30af\u30ea\u30c3\u30af\u3057\u3066\u6307\u5b9a\u3092\u3057\u3066\u304f\u3060\u3055\u3044\u3002\u3059\u3067\u306b\u30d5\u30a9\u30eb\u30c0\u304c\u5b58\u5728\u3059\u308b\u5834\u5408\u306b\u306f\u4f55\u3082\u884c\u3044\u307e\u305b\u3093\u3002");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);
        _setFontForComponent(_nsButton2, "Lucida Grande", 13, Font.PLAIN);
        _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField0.setEditable(false);
            _nsTextField0.setOpaque(true);
            _nsTextField0.setText("");
            _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField0.setSelectable(true);
            _nsTextField0.setEnabled(true);
        }

        _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsButton0.setSize(77, 26);
        _nsButton0.setLocation(285, 354);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton0);
        _nsTextField1.setSize(468, 70);
        _nsTextField1.setLocation(34, 77);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField1);
        _nsButton2.setSize(133, 26);
        _nsButton2.setLocation(369, 354);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton2);
        _nsBox0.setSize(531, 5);
        _nsBox0.setLocation(-13, 42);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox0);
        _nsTextField0.setSize(333, 22);
        _nsTextField0.setLocation(37, 155);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField0);
        _nsButton3.setSize(137, 22);
        _nsButton3.setLocation(12, 355);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton3);
        _nsTextField2.setSize(167, 17);
        _nsTextField2.setLocation(22, 194);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField2);
        _nsTextField3.setSize(446, 22);
        _nsTextField3.setLocation(13, 14);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField3);
        _nsTextView0.setSize(462, 117);
        _nsTextView0.setLocation(36, 219);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextView0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextView0);
        _nsButton1.setSize(126, 26);
        _nsButton1.setLocation(376, 155);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton1);
        _nsTextField4.setSize(405, 16);
        _nsTextField4.setLocation(22, 53);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField4);
        _nsBox2.setSize(474, 5);
        _nsBox2.setLocation(24, 183);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox2);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(517, 390);
            _eoFrame0.setTitle("\u6700\u7d42\u78ba\u8a8d 4/4");
            _eoFrame0.setLocation(298, 210);
            _eoFrame0.setSize(517, 390);
        }
    }
}
